// templates/vue-ts/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import { onMounted } from "vue";

onMounted(() => {
  const script = document.createElement("script");

  script.src = "https://buttons.github.io/buttons.js";
  script.async = true;

  document.body.appendChild(script);
});
</script>

<template>
  <div class="bg-gray-800 h-screen text-white">
    <header class="py-16">
      <h1 class="text-5xl font-bold text-center mb-6">Create Tailwind</h1>
      <p className="text-center mb-6 text-xl">
        Please support this project by starring the repository on GitHub.
      </p>

      <div class="flex flex-row justify-center items-center gap-4">
        <a
          class="github-button"
          href="https://github.com/andrejjurkin/create-tailwind-app"
          data-color-scheme="no-preference: dark; light: dark; dark: dark;"
          data-icon="octicon-star"
          data-size="large"
          data-show-count="true"
          aria-label="Star andrejjurkin/create-tailwind-app on GitHub"
        >
          Star
        </a>
        <a
          class="github-button"
          href="https://github.com/andrejjurkin/create-tailwind-app/discussions"
          data-color-scheme="no-preference: dark; light: dark; dark: dark;"
          data-icon="octicon-comment-discussion"
          data-size="large"
          aria-label="Discuss andrejjurkin/create-tailwind-app on GitHub"
        >
          Discuss
        </a>
      </div>
    </header>

    <div class="flex gap-16 items-center justify-center">
      <a href="https://vitejs.dev" target="_blank">
        <img src="/vite.svg" class="w-24 h-24" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="w-24 h-24" alt="Vue logo" />
      </a>
    </div>
  </div>
</template>

// templates/react-ts/App.tsx
import React, { useEffect } from "react";

function App() {
  useEffect(() => {
    const script = document.createElement("script");

    script.src = "https://buttons.github.io/buttons.js";
    script.async = true;

    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  return (
    <div>
      <div className="h-screen bg-gradient-to-b from-gray-900 to-slate-800 flex flex-col text-white">
        <header className="py-16">
          <h1 className="text-5xl font-bold text-center mb-2">
            Create Tailwind
          </h1>
          <p className="text-center mb-6 text-xl">
            Please support this project by starring the repository on GitHub.
          </p>
          <div className="flex flex-row justify-center items-center gap-4">
            <a
              className="github-button"
              href="https://github.com/andrejjurkin/create-tailwind-app"
              data-color-scheme="no-preference: dark; light: dark; dark: dark;"
              data-icon="octicon-star"
              data-size="large"
              data-show-count="true"
              aria-label="Star andrejjurkin/create-tailwind-app on GitHub"
            >
              Star
            </a>
            <a
              className="github-button"
              href="https://github.com/andrejjurkin/create-tailwind-app/discussions"
              data-color-scheme="no-preference: dark; light: dark; dark: dark;"
              data-icon="octicon-comment-discussion"
              data-size="large"
              aria-label="Discuss andrejjurkin/create-tailwind-app on GitHub"
            >
              Discuss
            </a>
          </div>
        </header>

        <main className="flex-1">
          <section className="text-center">
            <h2 className="text-3xl font-medium text-center">
              React.js Project Created using{" "}
              <a
                href="https://vitejs.dev/"
                target="_blank"
                className="text-indigo-300"
              >
                Vite
              </a>
            </h2>
          </section>
        </main>

        <footer className="px-8 py-12 border-t border-gray-800">
          <div className="px-8 font-medium text-center">
            <a href="https://github.com/andrejjurkin/create-tailwind-app">
              Create Tailwind
            </a>
          </div>
        </footer>
      </div>
    </div>
  );
}

export default App;
